# Generated by Django 4.2 on 2023-04-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_inbound_amount_alter_inbound_inbound_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outbound',
            options={'ordering': ['-outbound_date']},
        ),
        migrations.AlterModelTable(
            name='outbound',
            table='outbound',
        ),
    ]
