# Generated by Django 4.2 on 2023-04-07 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_inbound_amount_alter_outbound_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.product', verbose_name='상품')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='수량')),
            ],
        ),
    ]
